apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: hostname-udp
  labels:
    cluster.open-cluster-management.io/placement: http-gateway
spec:
  gatewayClassName: acme-lb
  listeners:
  - name: example
    hostname: example.com
    protocol: UDP
    port: 80
