apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: invalid-listener-port
  labels:
    cluster.open-cluster-management.io/placement: http-gateway
spec:
  gatewayClassName: acme-lb
  listeners:
  - name: foo
    protocol: HTTP
    port: 123456789
